# Generated by Django 5.2.6 on 2025-09-21 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.AddField(
            model_name="payment",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите плательщика",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Плательщик",
            ),
        ),
    ]
