# Generated by Django 5.2.6 on 2025-09-24 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_remove_payment_user_payment_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(
                blank=True,
                help_text="Ссылка для оплаты (для платежа через платежную систему)",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите идентификатор сессии платежа",
                max_length=255,
                null=True,
                verbose_name="Идентификатор сессии",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите сумму оплаты в рублях",
                verbose_name="Сумма оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите плательщика",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Плательщик",
            ),
        ),
    ]
