# Определение события, установка максимального количества соединений
events {
    worker_connections 1024;
}

# Основной HTTP блок
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Определение сервера для Django-приложения
    upstream django {
        server web:8000;
    }

    # Настройка сервера: порт 80, имя сервера - по умолчанию, обработка запросов к статическим и медиафайлам
    server {
        listen 80;
        server_name _;

        location /static/ {
            alias /app/static/;
        }

        location /media/ {
            alias /app/media/;
        }

        # Проксирование остальных запросов к Django-приложению
        location / {
            proxy_pass http://django;
        }
    }
}
